FileVersion = 1
Dependencies = { corlib = "*", SDL3 = "*", ImGui = "*" }

[Project]
Name = "ImGuiImplSDLGPU3"
DefaultNamespace = "ImGui"

[Configs.Debug.Win64]
LibPaths = [ "$(ProjectDir)/../dist/$(Configuration)-$(Platform)/cimgui.lib" ]
