FileVersion = 1
Projects = {ImGui-SDL3 = {Path = "."}, SDL3 = {Path = "SDL3-Beef"}, ImGui = {Path = "imgui-beef"}, ImGuiImplSDL3 = {Path = "imgui-beef/ImGuiImplSDL3"}, ImGuiImplSDLGPU3 = {Path = "imgui-beef/ImGuiImplSDLGPU3"}}

[Workspace]
StartupProject = "ImGui-SDL3"
